### ISSUE TITLE
Error starting plugin system

### ISSUE THREAD

**Issue by tyrel** [kierenj/0x10c-DevKit#64]
In 1.7 Preview, immediately upon starting up, I get the following dialog box:

> Error starting plugin system:
> 
> Devkit.Core.DevkitException: No plugin with guid b4c5440-2eca-490c-bb26-e7e1d9563667 was found ready to load.
>  at Devkit.IDE.ViewModel.PluginManager.LoadPlugin(Guid guid)
>  at Devkit.IDE.ViewModel.PluginManager.Autoload()
>  at Devkit.IDE.ViewModel.PluginManager.Startup()
>  at Devkit.IDE.MainWIndow.StartPluginSystem()

I tried removing different plugins from the plugin-config.xml and it didn't make a difference -- this happens with all the plugins.

Windows 7 SP1, 64-bit

**Comment by tyrel** [comment]
Viewing file properties and hitting "Unblock" on every DLL and EXE in the folder solved it.
